### ISSUE TITLE
Link not working. Page not found for create Application

### ISSUE THREAD

**Issue by nrup-parikh-indianic** [coinbase/coinbase-android-sdk#10]
https://www.coinbase.com/oauth/applications

This link shows
"PAGE NOT FOUND"
"Sorry we couldn't find what you were looking for."

So how can we create application in coinbase to test the SDK ?

**Comment by pan-long** [comment]
The link is broken, use https://www.coinbase.com/oauth/applications/new

Pull request created:
https://github.com/coinbase/coinbase-android-sdk/pull/12

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
