### ISSUE TITLE
redirect to app after email verification

### ISSUE THREAD

**Issue by uzairaslam93** [coinbase/coinbase-android-sdk#11]
i m redirecting to my app using intent filters after user has verified his email but query parameter state and code are missing in the redirect uri. Can anyone help me on this?

**Comment by adritung** [comment]
@uzairaslam93 I'm having the same issue.. did you manage to solve it somehow?

**Comment by uzairaslam1993** [comment]
yes I did Adrian. whats the exact issue that you are facing ? are you using their sdk?

**Comment by adritung** [comment]
yes, I'm using their SDK and I'm getting an exception after the email verification redirect: "CSRF detected!". I believe it's because of the missing state

**Comment by uzairaslam1993** [comment]
while coming from the email verification flow intent.getextras is different. you have to detect that and open the login screen of coinbase sdk

**Comment by adritung** [comment]
I see, thanks for your help!

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
