### ISSUE TITLE
unable to merge dex error with Android Studio 3

### ISSUE THREAD

**Issue by das-debdeep** [coinbase/coinbase-android-sdk#13]
When using  compile 'com.coinbase.android:coinbase-android-sdk:1.0.1' on Android Studio 3.0.1, I am getting error Unable to merge dex

**Comment by fatherOfLegends** [comment]
Same issue, if you exclude the duplicate module then you get a runtime crash.

**Comment by ashishparmar** [comment]
When using compile 'com.coinbase.android:coinbase-android-sdk:1.0.1' on Android Studio 3.0.1, I am getting error Unable to merge dex

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
