### ISSUE TITLE
Error:Program type already present: org.apache.http.ContentTooLongException

### ISSUE THREAD

**Issue by sahaab** [coinbase/coinbase-android-sdk#15]
Error:Program type already present: org.apache.http.ContentTooLongException

I get this error when I try to compile my app after importing the library (with nothing written in the code for coinbase).

`
AGPBI: {"kind":"error","text":"Program type already present: org.apache.http.ContentTooLongException","sources":[{}],"tool":"D8"}

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
`

**Comment by Bjelijah** [comment]
httpcore and httpclient-android lib both have ContentTooLongException.java check the version or do not implementation at same time

**Comment by khuranakaran** [comment]
Anyone found any solution to it ?

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
