### ISSUE TITLE
Error:Program type already present: org.apache.http.auth.AuthSchemeProvider

### ISSUE THREAD

**Issue by sahaab** [coinbase/coinbase-android-sdk#16]
When I add the dependency into my project, i get the error

> Error:Program type already present: org.apache.http.auth.AuthSchemeProvider

upon compiling.

Adding SDK using 
`
    compile ('com.coinbase.android:coinbase-android-sdk:1.0.1')
`

This occurs in the Android SDK Example As well

Does anyone have a fix for this?

**Comment by sahaab** [comment]
```
    compile ('com.coinbase.android:coinbase-android-sdk:1.0.1'){
        exclude group: 'org.apache.httpcomponents', module:'httpclient'
    }
```

Found this to be the answer

**Comment by abiemann** [comment]
implementation ('com.coinbase.android:coinbase-android-sdk:1.0.1'){
        exclude group: 'org.apache.httpcomponents', module:'httpclient'
    }

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
