### ISSUE TITLE
Error: Program type already present: org.apache.http.HeaderElementIterator

### ISSUE THREAD

**Issue by dzoelthomas** [coinbase/coinbase-android-sdk#18]
Hi.. I am a starter in android development. I tried to run my android emulator in  Linux for a project I just created and got this error.

Error: Program type already present: org.apache.http.HeaderElementIterator

I find it really confused to solve this problem. Can anyone help me out??Please?

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
