### ISSUE TITLE
Is this supposed to open up the Coinbase native app (if installed) when initiating OAuth authentication?

### ISSUE THREAD

**Issue by pgorsira** [coinbase/coinbase-android-sdk#3]
Because if so, it's not working for me. Nexus 7 with Android 5.1 as test device. Our app always redirects to coinbase.com in Chrome, even if the native Android Coinbase app is installed on the device.

I saw that the only open pull request (https://github.com/coinbase/coinbase-android-sdk/pull/2) is supposed to fix this, however, I've integrated those changes to no avail (still not opening in the native app). Any idea on the status of this situation? Is the PR bad? Is it something on my side? Thanks.

**Comment by aianus** [comment]
No, this is not yet supported.

**Comment by h2non** [comment]
Any updates here?
