### ISSUE TITLE
Mutiple dependencies of httpclient causes conflicts

### ISSUE THREAD

**Issue by jonalmeida** [coinbase/coinbase-android-sdk#4]
From what I can tell we have two httpclients being packaged:
 1. The one from [coinbase-java][1]
 2. The android port used in this sdk: [httpclient-android][2]

This causes conflicts when building a project with android-gradle (used in Android Studio):
```
Warning:Dependency org.apache.httpcomponents:httpclient:4.3.6 is ignored for release as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage it with jarjar to change the class packages
```
### STR
 1. Create a blank Android project with Android Studio (current stable is `1.3.2`)
 2. In the `app/build.gradle` add the coinbase android sdk as mentioned [in the docs][3]. 
 3. Sync project to pull dependencies.
 4. Build.
 5. Observe the error output as seen above.
 6. (optional) Cry.

[1]: https://github.com/coinbase/coinbase-java/blob/master/pom.xml#L108
[2]: https://github.com/coinbase/coinbase-android-sdk/blob/master/pom.xml#L74
[3]: https://github.com/coinbase/coinbase-android-sdk#using-maven

**Comment by jonalmeida** [comment]
After comparing my project with the example android project, I've narrowed down the problem being between the httpclient in coinbase-java and the android appcompat-v7 library. Removing appcompat stops the build failures but you lose compatibility. 

¯\_(ツ)_/¯

**Comment by aianus** [comment]
It's just a warning, you can ignore it can't you?

```
Warning:Dependency org.apache.httpcomponents:httpclient:4.3.6 is ignored for release as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage it with jarjar to change the class packages
```

^ it seems to be doing the correct thing here (ignoring the incompatible dependency) by default.

**Comment by jonalmeida** [comment]
Okay, I think in my sleeplessness at a hackathon during the weekend, I wasn't looking into the errors properly.

Excluding the license files in the gradle file seems to have fixed the issue..

Sorry, ignore this!
