### ISSUE TITLE
Update jcenter with latest (1.0.2) build of sdk

### ISSUE THREAD

**Issue by jonalmeida** [coinbase/coinbase-android-sdk#6]
The docs all point to using version 1.0.1, but building the sdk manually let's you use the updated library instead. Updating the lib at jcenter would let you use the up-to-date version via gradle.

**Comment by aianus** [comment]
There is no v1.0.2. The version on master is 1.0.2-SNAPSHOT in anticipation of a future v1.0.2 release but the only commit since v1.0.1 is a README change.
