### ISSUE TITLE
Sending Bitcoin Problem

### ISSUE THREAD

**Issue by iArsalanshah** [coinbase/coinbase-android-sdk#8]
Hello 
I'm using this dependency compile ('com.coinbase.android:coinbase-android-sdk:1.0.1')
and current android sdk is 25

I'm trying to send bitcoin (after OAuth2 token)

using:

Transaction t = new Transaction();
t.setTo("emailAddress");
t.setAmount(Money.parse("BTC 0.001"));
t.setNote("notes to send");
cb = new CoinbaseBuilder().withAccessToken(tokens.getAccessToken()).build();
cb.sendMoney(t);
but it returns this java.io.FileNotFoundException: https://coinbase.com/api/v1/transactions/send_money

i also have set Internet Permission in Manifest, is there anything missing? i need to resolve this ASAP
Thanks

**Comment by nzwelly567** [comment]
Did you find the answer to your question?

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
