### ISSUE TITLE
Scope do not match the current API version.

### ISSUE THREAD

**Issue by Boominfotech** [coinbase/coinbase-android-sdk#9]
Hi, I am using the Coinbase SDK for android.

My project dependency is: 
compile('com.coinbase.android:coinbase-android-sdk:1.0.1') {
        exclude module: 'httpclient' //by artifact name
        exclude group: 'org.apache.httpcomponents' //by group
        exclude group: 'org.apache.httpcomponents', module: 'httpclient' //by both name and group
    }

I was unable to get Access token by using this statement: 
OAuth.beginAuthorization(this, CLIENT_ID, "user", REDIRECT_URI, null);

Application crashes when the SDK tries to get Authorization URI using: 
 URI authorizationUri = coinbase.getAuthorizationUri(request);// code from sdk's Auth.java

I believe it was happening because we are passing the OAuthCodeRequest.Meta as null. Anyways I don't know the solid reason here.

So somehow I managed to create an access token by using this code manually:
String auth_url = "https://www.coinbase.com/oauth/authorize?" +
              "client_id=" +CLIENT_ID +
              "&redirect_uri=" + REDIRECT_URI +
              "&response_type=code" +
              "&scope=wallet:user:read";
      Log.e("TAG", "onCreate: "+ auth_url );
      URI authorizationUri = URI.create(auth_url);
      Intent i = new Intent(Intent.ACTION_VIEW);
      Uri androidUri = Uri.parse(authorizationUri.toString());
      androidUri = androidUri.buildUpon().appendQueryParameter("state", getLoginCSRFToken(MainActivity.this)).build();
      i.setData(androidUri);
      startActivity(i);

It successfully returns me the access token. But finally when I try to get the user instance using this code snippet:
String token = tokens.getAccessToken();
            Coinbase cb = new CoinbaseBuilder()
                    .withAccessToken(token)
                    .build();
            Log.e("Email", "doInBackground: "+cb.getUser().getEmail());
It gives me this exception:

com.coinbase.api.exception.CoinbaseException: Bereiken komen niet overeen met de huidige API-versie.
OR
com.coinbase.api.exception.CoinbaseException: Scope does not match the current API version.

Can anybody help me in this?

Many Thanks!!

**Comment by bes89** [comment]
Same issue using api key + api secret

**Comment by StephenMilone** [comment]
This SDK needs a v1 API created, v2 will result in this error.  Also note v1 will only return BTC accounts, not ETH/LTC.

**Comment by jaiishankar** [comment]
What is the way out for this issue? can we send the API version?

**Comment by johnnylambada** [comment]
@jaiishankar you set the API Version by choosing it in your import:

`import org.knowm.xchange.coinbase.v2.CoinbaseExchange;`

instead of 

`import org.knowm.xchange.coinbase.CoinbaseExchange;`

**Comment by yeikel** [comment]
Any update?

**Comment by lumyus** [comment]
> This SDK needs a v1 API created, v2 will result in this error. Also note v1 will only return BTC accounts, not ETH/LTC.
This is exactly my problem right now. Any update?

**Comment by mhd-zulqarnain** [comment]
I get the access token in intent data and in ActivityBlank and get the email and amount wallet code link
`redirect activity will be changed in manifest

<activity android:name=".Blank">

            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data
                    android:pathPrefix="coinbase-oauth"
                    android:scheme="coinbase-android-example"
                    tools:ignore="AppLinkUrlError" />
            </intent-filter>`

[https://github.com/mhd-zulqarnain/coinbase_api/blob/get_wallet/app/src/main/java/com/example/zulqurnain/coinbaseapi/Blank.java](url)

but have same issue it only return BTC accounts, not ETH/LTC.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
